[build]
  environment = { NODE_VERSION = "20.11.1" }
  command = "npm ci && expo build:web" # Replace with your actual build command
  publish = "web-build" # Replace with your actual publish directory
